# Generated by Django 5.1.4 on 2024-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
