# Generated by Django 5.1.4 on 2024-12-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_factura_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
    ]
