# Generated by Django 5.1.4 on 2025-01-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_venta_cliente'),
    ]

operations = [
    migrations.RemoveField(
        model_name='factura',
        name='numero',
    ),
    migrations.AddField(
        model_name='factura',
        name='cliente',
        field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='venta',
        name='cliente',
        field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.cliente'),
        preserve_default=False,
    ),
    migrations.AlterField(
        model_name='factura',
        name='imagen',
        field=models.ImageField(default='media/imagenes/default.jpg', upload_to='facturas/'),
        preserve_default=False,
    ),
    migrations.AlterField(
        model_name='factura',
        name='venta',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
    ),
]
