# Generated by Django 5.1.4 on 2025-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_factura_numero_factura_cliente_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
