# Generated by Django 5.1.4 on 2025-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_detalleventa_options_alter_factura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cedula_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], default='efectivo', max_length=10),
        ),
    ]
