# Generated by Django 5.1.4 on 2024-12-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('ventas_totales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos_mas_vendidos', models.TextField()),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recomendaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
