# Generated by Django 5.1.4 on 2024-12-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='7664139645:AAGKeuPU8NOJs2rva26iLIVSZ-yhXoieJSo', max_length=200)),
                ('chat_id', models.CharField(help_text='6210283564', max_length=50)),
            ],
        ),
    ]
