# Generated by Django 5.1.4 on 2025-01-13 23:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_reportefinanciero_delete_analisisdiario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefinanciero',
            name='costos_compras',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='reportefinanciero',
            name='costos_nomina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='reportefinanciero',
            name='ingresos_ventas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='reportefinanciero',
            name='margen_utilidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportefinanciero',
            name='utilidad_bruta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
