# Generated by Django 5.1.4 on 2024-12-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_impuestosmensuales_empleado_registrohoras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='Empleado sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
