# Generated by Django 5.1.4 on 2024-12-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_empleado_usuario_empleado_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
    ]
