# Generated by Django 5.1.4 on 2025-01-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_perfil_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='salario_por_hora',
            new_name='salario_por_dia',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='horas_trabajadas',
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='dias_trabajados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
