# Generated by Django 5.1.4 on 2025-01-12 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_registrohoras_hora_fin_registrohoras_hora_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='salario_por_dia',
            new_name='salario_por_hora',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='dias_trabajados',
        ),
        migrations.RemoveField(
            model_name='registrohoras',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
