# Generated by Django 5.1.4 on 2025-01-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_salario_por_dia_empleado_salario_por_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='registrohoras',
            options={'verbose_name': 'Registro de Horas', 'verbose_name_plural': 'Registros de Horas'},
        ),
    ]
